services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - network

volumes:
  caddy_data:
  caddy_config:

networks:
  network:
    driver: bridge
